"""Exports evidence/pitch_demo.json (written by pitch_demo.py) into the Remotion scenes' data module.

Every curve and number the pitch scenes draw comes from that real run: the sung melody's measured
pitch, the targets, and the pitch RE-MEASURED after each correction. The cents equation in B03 is
typeset with the toolkit's own runtime/scripts/typeset_math.py (MathText -> outlined SVG) and its
numbers are computed here from the measured frequency, never typed in. Run after pitch_demo.py:

    python export_pitch_data.py
"""
import hashlib
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLKIT = os.path.normpath(os.path.join(HERE, "../../../../../HAI/RohanClaudeHAIbrutalist.art"))
EV = os.path.join(HERE, "evidence")
OUT_TS = os.path.join(TOOLKIT, "runtime/remotion/src/scenes/pitch/pitchData.ts")

sys.path.insert(0, os.path.join(TOOLKIT, "runtime/scripts"))
sys.path.append(os.path.join(TOOLKIT, ".pydeps"))  # matplotlib for the house math renderer
from typeset_math import typeset  # noqa: E402

D = json.load(open(os.path.join(EV, "pitch_demo.json"), encoding="utf-8"))
W = D["worked_example"]

# the worked example, recomputed from the measured period so every shown digit agrees
f = 22050 / W["period_samples"]
cents = 1200 * math.log2(f / W["nearest_hz"])
assert abs(cents - W["cents"]) < 0.06, (cents, W["cents"])
eq = {
    "rule": typeset(r"c = 1200\,\log_2\!\left(\frac{f}{f_{\mathrm{note}}}\right)"),
    "worked": typeset(r"1200\,\log_2\!\left(\frac{" + f"{f:.2f}" + r"}{" + f"{W['nearest_hz']:.1f}" + r"}\right) \approx "
                      + f"{cents:.1f}".replace("-", "-")),
}


def q(a, nd=2):
    return [round(x, nd) for x in a]


runs = {k: {"tau": v["tau_ms"], "scale": v["scale"], "meanErr": v["mean_err_cents"],
            "medianErr": v["median_err_cents"], "lastNote": v["last_note_after"],
            "after": q(v["f0_measured_after_hz"], 1), "target": [int(t) for t in v["target_midi"]]}
        for k, v in D["runs"].items()}

data = {
    "hop": D["hop"], "sr": D["sr"], "frame": D["frame"],
    "melody": D["melody"],
    "times": q(D["times"], 4),
    "sung": q(D["f0_sung_hz"], 1),
    "runs": runs,
    "beforeMeanErr": D["before_mean_err_cents"],
    "detectorMedianErr": D["detector_median_err_cents"],
    "worked": {**W, "f": round(f, 2), "centsExact": round(cents, 2), "periodMs": round(1000 * W["period_samples"] / 22050, 3)},
    "eq": eq,
    "evidenceSha256": hashlib.sha256(open(os.path.join(EV, "pitch_demo.json"), "rb").read()).hexdigest(),
}
os.makedirs(os.path.dirname(OUT_TS), exist_ok=True)
with open(OUT_TS, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("/* GENERATED by export_pitch_data.py in the reel folder\n"
             " * (books/humanitarians-ai/youtube/week-06/2026-10-02-how-pitch-correction-works).\n"
             " * Every curve and number here comes from a real run of pitch_demo.py (YIN detection,\n"
             " * snap, glide, TD-PSOLA, then re-measured). Do not hand-edit; re-run the exporter. */\n")
    fh.write("export const PITCH = " + json.dumps(data, separators=(",", ":")) + ";\n")
print(f"worked example: f={f:.2f} Hz, {cents:.2f} cents vs {W['nearest']} {W['nearest_hz']} Hz")
print(f"wrote {OUT_TS} ({os.path.getsize(OUT_TS)/1024:.0f} KB)")
